common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views


app_name='common'

urlpatterns=[
    path('login/', auth_views.LoginView.as_view(
            template_name='common/login.html'),name='login'),
    path('logout/', views.logout_view, name='logout'),
    #path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup' ),
    path('item/',views.item_inventory, name='item_list' ),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo import views





urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index'),
    path('item/',views.index, name='item.list'),


]

pybo/urls.py
from django.urls import path

from. import views



app_name='pybo'

urlpatterns=[
    
    path('',views.index, name='index' ),



]

common/models.py
from django.db import models

# Create your models here.

pybo/models.py
from django.db import models

import os
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'projects.settings')

class Inventory(models.Model):
    category = models.CharField(max_length=100)
    product_model = models.CharField(max_length=100)
    creation_date = models.CharField(max_length=100)
    task_type = models.CharField(max_length=100)
    version_capacity = models.CharField(max_length=100)
    amount = models.CharField(max_length=100)
    in_out_date = models.CharField(max_length=100)
    remark = models.CharField(max_length=100)
    production_quantity = models.CharField(max_length=100)
    delivery_quantity = models.CharField(max_length=100)
    as_in_quantity = models.CharField(max_length=100)
    as_repair_quantity = models.CharField(max_length=100)
    as_out_quantity = models.CharField(max_length=100)
    input_complete = models.CharField(max_length=100)
    final_edit_timestamp = models.CharField(max_length=100)
    as_replacement = models.CharField(max_length=100)

Inventory.objects.create(category ='속성')
# Create your models here

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    email=forms.EmailField(label="이메일")
    
    class Meta:
        model= User
        fields=("username", "email")
        

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm
from django.contrib.auth import logout
from django.shortcuts import redirect
def signup(request):
    
    if request.method =="POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username= form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user=authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form= UserForm()
    return render(request,'common/signup.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('index')

def item_inventory(request):
    csv_file_path ="C:\projects"
    
    return render(request, 'item_list.html')
# Create your views here.

pybo/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.utils import timezone

import os
#import pandas as pd
#df = pd.read_csv('inventory.csv', encoding='cp949')

#def download_csv(request):
    # Update the path to reflect the correct directory structure
    #file_path = os.path.join('C:\\projects', 'inventory.csv')

    #with open(file_path, 'rb') as file:
        #response = HttpResponse(file.read(), content_type='text/csv')
        #response['Content-Disposition'] = 'attachment; filename="inventory.csv"'
        #return response
import csv

file =open("inventory.csv", newline='')
reader = csv.reader(file)
for i, line in enumerate(reader):
    if i ==2:
        break
    print(line[0],line[1],line[2],line[3],line[4],line[5],line[6],line[7],line[8],line[9],line[10],line[11],line[12],line[13],line[14],line[15],sep='/')
    print('데이터출력')
def index(request):
    return HttpResponse("안녕하세요 pybo에 오신것을 환영합니다.")

templates/base.html
<!-- myapp/templates/base.html -->
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello pybo!</title>
</head>
<body>
{%include "navbar.html"%}

<!--<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'pybo:index' %}"> Pybo</a>
    <button class="navbar-toggler ml-auto" type="button"
                data-toggle="collapse"
                data-target="#navbarNav"
                aria-controls="navbarNav"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="#">로그인</a>
            </li>
        </ul>
    </div>
</nav>
-->
{%block content%}
{% endblock %}
<script src="{% static 'jquery-3.4.1.min.js'%}"></script>
<script src="{% static 'bootstrap.min.js'%}"></script>
</body>
</html>

templates/common/login.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends "base.html"%}
    {% block content%}
    <div class="container my-3">
        <div class="row">
            <div class="col-4">
                <h4>로그인</h4>
            </div>
            <div class="col-8 text-right">
                <span>
                    또는 <a href="{% url 'common:signup'%}">계정을 만드세요.</a>
                </span>
            </div>
        </div>
    
        <form method="post" class ="post-form" action="{%url 'common:login'%}">
            {%csrf_token%}
            {% include "form_errors.html"%}
            <div class ="form-group">
                    <label for="username">사용자ID</label>
                    <input type ="text" class="form-control" name="username" id="username"
                            value="{{form.username.value|default_if_none:''}}">
            </div>
            <div class="form-group">
                <label for="password">비밀번호</label>
                <input type ="password" class="form-control" name="password" id="password"
                        value="{{form.password.value|default_if_none:''}}">
            </div>
            <button type="submit" class="btn btn-primary">로그인</button>
        </form>
    </div>
    {%endblock%}  
</body>
</html>


    

templates/common/signup.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends "base.html"%}
    {%block content%}
    <div class="container my-3">
        <div class="row my-3">
            <div class="col-4">
                <h4>회원가입</h4>
            </div>
            <div class="col-8 text-right">
                <span>또는 <a href="{% url 'common:login'%}">로그인 하세요.</a></span>
            </div>
        </div>
        <form method="post" class="post-form">
            {% csrf_token%}
            {%include "form_errors.html"%}
            <div class="form-group">
                <label for="username">사용자 이름</label>
                <input type = "text" class="form-control" name="username" id="username"
                        value ="{{form.username.value| default_if_none:''}}">
            </div>
            <div class="form-group">
                <label for="password1">비밀번호</label>
                <input type="password" class="form-control"
                        name="password1" id="password1"
                        value="{{form.password1.value|default_if_none:''}}">
            </div>
            <div class="form-group">
                <label for="password2">비밀번호 확인</label>
                <input type="password" class="form-control"
                        name="password2" id="password2"
                        value="{{form.password2.value|default_if_none:''}}">
            </div>
            <div class="form-group">
                <label for="email">이메일</label>
                <input type="text" class="form-control" name="email" id="email"
                        value="{{form.email.value|default_if_none:''}}">
            </div>
            <button type="submit" class="btn btn-primary">생성하기</button>
        </form>
    </div>
    {% endblock %}
    
</body>
</html>

templates/form_errors.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Document</title>
</head>
<body>
    {% if form.errors%}
        {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field.label}}</strong>
                {{error}}
            </div>
        {%endfor%}
    {%endfor%}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{error}}</strong>
            </div>
        {% endfor %}
    {% endif %}
</body>
</html>

templates/item_list.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<style>
        .table1{
            border: 1px solid black;
            padding:10px;
            text-align:center;
    }
        th, td{
            border: 1px solid black;
            padding:10px;
            text-align:center;
    }
</style>
<body>
        <div class="table-responsive-lg">
            <table class="table1">
            <caption>재고관리 리스트</caption>
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">First</th>
                    <th scope="col">Last</th>
                    <th scope="col">Handle</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">1</th>
                    <td>dd</td>
                    <td>dd</td>
                    <td>dd</td>
                    <td>dd</td>
                </tr>
            </tbody>
            <tfoot>
                <tr>
                    <th scope="row">2</th>
                    <th>dd</th>
                    <th>dd</th>
                    <th>dd</th>
                    <th>dd</th>
                </tr>
                <tr>
                    <th scope="row">3</th>
                    <th>dd</th>
                    <th>dd</th>
                    <th>dd</th>
                    <th>dd</th>
                </tr>
                <tr>
                    <th scope="row">4</th>
                    <th>dd</th>
                    <th>dd</th>
                    <th>dd</th>
                    <th>dd</th>
                </tr>
            </tfoot>
            </table>
        <div/>
</body>
</html>

templates/navbar.html
<!-- myapp/templates/base.html -->
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello pybo!</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
        <a class="navbar-brand" href="{% url 'pybo:index' %}"> Pybo</a>
        <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse"
                data-target="#navbarNav" aria-controls="navbarNav"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout'%}">
                        {{user.username}} (로그아웃)
                    </a>
                    {%else%}
                    <a class="nav-link" href="{%url 'common:login'%}">로그인</a>
                    {%endif%}
                </li>
            </ul>
        </div>
    </nav>
</body>
</html>